#명령어: docker-compose up
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cosy-pet
    #컨테이너 닫혔을때 연결되는 포트 번호
    ports:
      - '3000:3000'
    #app을 찾을 위치
    volumes:
      - .:/app
      - /app/node_modules
    
      
      