# Workflow name
name: 'Chromatic Deployment'

# Event for the workflow
on: 
  push:   
    branches: 
      - main #메인 브랜치에 푸시될 때마다 깃 action 활성화

# List of jobs
jobs:
  test:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1

      - name: .env setting
        env: 
          NEXT_PUBLIC_STORYBOOK_FIGMA_ACCESS_TOKEN: ${{ secrets.NEXT_PUBLIC_STORYBOOK_FIGMA_ACCESS_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        run: |
          echo 토큰값 : $NEXT_PUBLIC_STORYBOOK_FIGMA_ACCESS_TOKEN
          echo $NEXT_PUBLIC_STORYBOOK_FIGMA_ACCESS_TOKEN >> .env
          echo projectToken=$CHROMATIC_PROJECT_TOKEN >> .env

      # - name: install library
      #   run: yarn
      # - uses: chromaui/action@v1
      #   name: deploy chromatic
      #   # Options required for Chromatic's GitHub Action
      #   with:
      #     #👇 Chromatic projectToken, see https://storybook.js.org/tutorials/intro-to-storybook/react/ko/deploy/ to obtain it
      #     projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
      #     token: ${{ secrets.GITHUB_TOKEN }}